name: Build Flowchart

on:
  push:
    branches:
      - main

jobs:
  build-flowchart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Git Flowchart
      run: |
        wget https://github.com/camillescriven/git-flowchart/releases/latest/download/git-flowchart -O /usr/local/bin/git-flowchart
        chmod +x /usr/local/bin/git-flowchart

    - name: Generate Flowchart
      run: git-flowchart -o flowchart.png

    - name: Upload Flowchart
      uses: actions/upload-artifact@v3
      with:
        name: flowchart
        path: flowchart.png