name: Generate Commit Flowchart

on:
  push:

jobs:
  generate-flowchart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Generate flowchart
      run: |
        git log --pretty=format:'%h %ad | %s%d [%an]' --date=short --all | \
        gawk '{$1=$1; print | "dot -Tpng"}' > commit-flowchart.png

    - name: Upload flowchart as artifact
      uses: actions/upload-artifact@v2
      with:
        name: commit-flowchart
        path: commit-flowchart.png