name: Update Workflow Diagram

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate Workflow Diagrams
        run: |
          for file in .github/workflows/*.yml; do
            npx mmdc -i "$file" -o "${file%.yml}.svg"
          done
